### PR TITLE
APPW-4366: Add Code Linter To utopia-php/audit

### PR DESCRIPTION
**Pull request by Rutam21**
## What

This PR aims to resolve the issue https://github.com/appwrite/appwrite/issues/4366.

## How

- Code Linter has been added to utopia-php/audit repository.
- All existing files are formatted as per the Linting rules.
- PR Template has been followed as mentioned in https://github.com/utopia-php/ab/pull/7.

Fixes https://github.com/appwrite/appwrite/issues/4366

### CODE REVIEW

**Comment by Rutam21** [comment]
@Meldiron Please review and approve or suggest changes, if any. Thanks.

**Review by Meldiron — APPROVED** [review]
Looks great 🎉

**Comment by Rutam21** [comment]
@Meldiron I hope this can be merged now and the respective issue can be marked as complete and closed.

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
@Rutam21. sorry, it looks like there are merge conflicts now. Would you please resolve them?

**Comment by Rutam21** [comment]
@stnguyen90 I have resolved the merge conflicts. This is good to be merged now. LMK if any further changes are needed.

**Review by stnguyen90 — APPROVED** [review]
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
