### PR TITLE
Pagination and new function

### PR DESCRIPTION
**Pull request by lohanidamodar**
- Adds pagination to different Get logs methods
- Adds new method and relevant indexes to get logs by `resource` and `events`

### CODE REVIEW

**Review by eldadfux — CHANGES_REQUESTED** [review]
Changes look great, let's add some tests to cover new functionality.

**Review by TorstenDittmann — APPROVED** [review]
Looks good, once tests are added there is one thing.

Do we want to check if the `after` document exists?

**Comment by lohanidamodar** [comment]
> after

Not sure I understand?

**Comment by TorstenDittmann** [comment]
> > after
> 
> Not sure I understand?

Nevermind, is too early for me 👍🏻

**Review by eldadfux — APPROVED** [review]

**Pull request merged**
